#!/usr/bin/expect

	set remote_server [lindex $argv 0]
	set my_user_id root
	set my_password root
	set my_command fhw
	######################################################################################
	#$remote_server - сервер, к которому осуществляется доступ                           #
	#$my_user_id    - имя пользователя на сервере                                        #
	#$my_password   - пароль пользователя на сервере                                     #
	#$my_command    - команда, которая будет запущена на сервере                         #
	#                                                                                    #
	# Предполагается, что $remote_server, $my_user_id, $my_password, и $my_command       #
	# были инициализированы в скрипте ранее.                                             #
	######################################################################################
	# Открываем telnet сессию на удалённом сервере, и ждем запроса имени пользователя.
	spawn telnet $remote_server
	expect {
	"telnet:*" { close }
	"login:" {
	# Посылаем имя пользователя и ждем запроса пароля.
	send "$my_user_id\r" 
	expect "Password:"
	# Посылаем пароль и ждем приглашения ввода командного интерпретатора.
	send "$my_password\r"
	expect "#"
	send ". fc\r"
	expect "#"
	# Посылаем команду, и ждем следующего приглашения ввода командного интерпретатора.
	send "$my_command\r"
	expect "#"
	# Запоминаем результат в переменной. Он может быть отображён, или записан на диск.
	#set results $expect_out(buffer)
	# Завершаем сессию telnet, и ждем символа конца строки (eof).
	interact }} 
	#send "exit\r"
	#expect eof
